// flow-typed signature: 1c3398d3ba5e24cfc05bf766f7d8e8c5
// flow-typed version: <<STUB>>/eslint-plugin-jsx-a11y_v1.3.0/flow_v0.53.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-jsx-a11y'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-jsx-a11y' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-plugin-jsx-a11y/lib/index' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/lib/rules/aria-props' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/lib/rules/aria-proptypes' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/lib/rules/aria-role' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/lib/rules/aria-unsupported-elements' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/lib/rules/href-no-hash' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/lib/rules/img-has-alt' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/lib/rules/img-redundant-alt' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/lib/rules/label-has-for' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/lib/rules/mouse-events-have-key-events' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/lib/rules/no-access-key' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/lib/rules/no-onchange' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/lib/rules/onclick-has-focus' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/lib/rules/onclick-has-role' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/lib/rules/role-has-required-aria-props' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/lib/rules/role-supports-aria-props' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/lib/rules/tabindex-no-positive' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/lib/util/getAttribute' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/lib/util/getAttributeValue' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/lib/util/getImplicitRole' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/lib/util/getNodeType' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/lib/util/getSuggestion' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/lib/util/getTabIndex' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/lib/util/implicitRoles/a' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/lib/util/implicitRoles/area' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/lib/util/implicitRoles/article' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/lib/util/implicitRoles/aside' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/lib/util/implicitRoles/body' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/lib/util/implicitRoles/button' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/lib/util/implicitRoles/datalist' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/lib/util/implicitRoles/details' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/lib/util/implicitRoles/dialog' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/lib/util/implicitRoles/dl' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/lib/util/implicitRoles/form' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/lib/util/implicitRoles/h1' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/lib/util/implicitRoles/h2' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/lib/util/implicitRoles/h3' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/lib/util/implicitRoles/h4' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/lib/util/implicitRoles/h5' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/lib/util/implicitRoles/h6' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/lib/util/implicitRoles/hr' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/lib/util/implicitRoles/img' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/lib/util/implicitRoles/index' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/lib/util/implicitRoles/input' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/lib/util/implicitRoles/li' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/lib/util/implicitRoles/link' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/lib/util/implicitRoles/menu' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/lib/util/implicitRoles/menuitem' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/lib/util/implicitRoles/meter' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/lib/util/implicitRoles/nav' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/lib/util/implicitRoles/ol' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/lib/util/implicitRoles/option' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/lib/util/implicitRoles/output' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/lib/util/implicitRoles/progress' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/lib/util/implicitRoles/section' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/lib/util/implicitRoles/select' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/lib/util/implicitRoles/tbody' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/lib/util/implicitRoles/textarea' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/lib/util/implicitRoles/tfoot' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/lib/util/implicitRoles/thead' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/lib/util/implicitRoles/ul' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/lib/util/isHiddenFromScreenReader' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/lib/util/isInteractiveElement' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/lib/util/values/expressions/BinaryExpression' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/lib/util/values/expressions/CallExpression' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/lib/util/values/expressions/ConditionalExpression' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/lib/util/values/expressions/FunctionExpression' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/lib/util/values/expressions/Identifier' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/lib/util/values/expressions/index' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/lib/util/values/expressions/LogicalExpression' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/lib/util/values/expressions/MemberExpression' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/lib/util/values/expressions/NewExpression' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/lib/util/values/expressions/ObjectExpression' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/lib/util/values/expressions/TemplateLiteral' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/lib/util/values/expressions/ThisExpression' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/lib/util/values/expressions/UnaryExpression' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/lib/util/values/index' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/lib/util/values/JSXElement' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/lib/util/values/Literal' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/src/index' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/src/rules/aria-props' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/src/rules/aria-proptypes' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/src/rules/aria-role' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/src/rules/aria-unsupported-elements' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/src/rules/href-no-hash' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/src/rules/img-has-alt' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/src/rules/img-redundant-alt' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/src/rules/label-has-for' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/src/rules/mouse-events-have-key-events' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/src/rules/no-access-key' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/src/rules/no-onchange' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/src/rules/onclick-has-focus' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/src/rules/onclick-has-role' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/src/rules/role-has-required-aria-props' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/src/rules/role-supports-aria-props' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/src/rules/tabindex-no-positive' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/src/util/getAttribute' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/src/util/getAttributeValue' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/src/util/getImplicitRole' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/src/util/getNodeType' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/src/util/getSuggestion' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/src/util/getTabIndex' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/src/util/implicitRoles/a' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/src/util/implicitRoles/area' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/src/util/implicitRoles/article' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/src/util/implicitRoles/aside' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/src/util/implicitRoles/body' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/src/util/implicitRoles/button' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/src/util/implicitRoles/datalist' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/src/util/implicitRoles/details' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/src/util/implicitRoles/dialog' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/src/util/implicitRoles/dl' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/src/util/implicitRoles/form' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/src/util/implicitRoles/h1' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/src/util/implicitRoles/h2' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/src/util/implicitRoles/h3' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/src/util/implicitRoles/h4' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/src/util/implicitRoles/h5' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/src/util/implicitRoles/h6' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/src/util/implicitRoles/hr' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/src/util/implicitRoles/img' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/src/util/implicitRoles/index' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/src/util/implicitRoles/input' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/src/util/implicitRoles/li' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/src/util/implicitRoles/link' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/src/util/implicitRoles/menu' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/src/util/implicitRoles/menuitem' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/src/util/implicitRoles/meter' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/src/util/implicitRoles/nav' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/src/util/implicitRoles/ol' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/src/util/implicitRoles/option' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/src/util/implicitRoles/output' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/src/util/implicitRoles/progress' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/src/util/implicitRoles/section' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/src/util/implicitRoles/select' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/src/util/implicitRoles/tbody' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/src/util/implicitRoles/textarea' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/src/util/implicitRoles/tfoot' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/src/util/implicitRoles/thead' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/src/util/implicitRoles/ul' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/src/util/isHiddenFromScreenReader' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/src/util/isInteractiveElement' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/src/util/values/expressions/BinaryExpression' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/src/util/values/expressions/CallExpression' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/src/util/values/expressions/ConditionalExpression' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/src/util/values/expressions/FunctionExpression' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/src/util/values/expressions/Identifier' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/src/util/values/expressions/index' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/src/util/values/expressions/LogicalExpression' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/src/util/values/expressions/MemberExpression' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/src/util/values/expressions/NewExpression' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/src/util/values/expressions/ObjectExpression' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/src/util/values/expressions/TemplateLiteral' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/src/util/values/expressions/ThisExpression' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/src/util/values/expressions/UnaryExpression' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/src/util/values/index' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/src/util/values/JSXElement' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/src/util/values/Literal' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/tests/index' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/tests/src/rules/aria-props' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/tests/src/rules/aria-proptypes' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/tests/src/rules/aria-role' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/tests/src/rules/aria-unsupported-elements' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/tests/src/rules/href-no-hash' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/tests/src/rules/img-has-alt' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/tests/src/rules/img-redundant-alt' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/tests/src/rules/label-has-for' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/tests/src/rules/mouse-events-have-key-events' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/tests/src/rules/no-access-key' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/tests/src/rules/no-onchange' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/tests/src/rules/onclick-has-focus' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/tests/src/rules/onclick-has-role' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/tests/src/rules/role-has-required-aria-props' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/tests/src/rules/role-supports-aria-props' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/tests/src/rules/tabindex-no-positive' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsx-a11y/tests/src/util/getSuggestion' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-plugin-jsx-a11y/lib/index.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/lib/index'>;
}
declare module 'eslint-plugin-jsx-a11y/lib/rules/aria-props.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/lib/rules/aria-props'>;
}
declare module 'eslint-plugin-jsx-a11y/lib/rules/aria-proptypes.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/lib/rules/aria-proptypes'>;
}
declare module 'eslint-plugin-jsx-a11y/lib/rules/aria-role.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/lib/rules/aria-role'>;
}
declare module 'eslint-plugin-jsx-a11y/lib/rules/aria-unsupported-elements.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/lib/rules/aria-unsupported-elements'>;
}
declare module 'eslint-plugin-jsx-a11y/lib/rules/href-no-hash.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/lib/rules/href-no-hash'>;
}
declare module 'eslint-plugin-jsx-a11y/lib/rules/img-has-alt.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/lib/rules/img-has-alt'>;
}
declare module 'eslint-plugin-jsx-a11y/lib/rules/img-redundant-alt.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/lib/rules/img-redundant-alt'>;
}
declare module 'eslint-plugin-jsx-a11y/lib/rules/label-has-for.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/lib/rules/label-has-for'>;
}
declare module 'eslint-plugin-jsx-a11y/lib/rules/mouse-events-have-key-events.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/lib/rules/mouse-events-have-key-events'>;
}
declare module 'eslint-plugin-jsx-a11y/lib/rules/no-access-key.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/lib/rules/no-access-key'>;
}
declare module 'eslint-plugin-jsx-a11y/lib/rules/no-onchange.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/lib/rules/no-onchange'>;
}
declare module 'eslint-plugin-jsx-a11y/lib/rules/onclick-has-focus.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/lib/rules/onclick-has-focus'>;
}
declare module 'eslint-plugin-jsx-a11y/lib/rules/onclick-has-role.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/lib/rules/onclick-has-role'>;
}
declare module 'eslint-plugin-jsx-a11y/lib/rules/role-has-required-aria-props.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/lib/rules/role-has-required-aria-props'>;
}
declare module 'eslint-plugin-jsx-a11y/lib/rules/role-supports-aria-props.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/lib/rules/role-supports-aria-props'>;
}
declare module 'eslint-plugin-jsx-a11y/lib/rules/tabindex-no-positive.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/lib/rules/tabindex-no-positive'>;
}
declare module 'eslint-plugin-jsx-a11y/lib/util/getAttribute.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/lib/util/getAttribute'>;
}
declare module 'eslint-plugin-jsx-a11y/lib/util/getAttributeValue.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/lib/util/getAttributeValue'>;
}
declare module 'eslint-plugin-jsx-a11y/lib/util/getImplicitRole.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/lib/util/getImplicitRole'>;
}
declare module 'eslint-plugin-jsx-a11y/lib/util/getNodeType.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/lib/util/getNodeType'>;
}
declare module 'eslint-plugin-jsx-a11y/lib/util/getSuggestion.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/lib/util/getSuggestion'>;
}
declare module 'eslint-plugin-jsx-a11y/lib/util/getTabIndex.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/lib/util/getTabIndex'>;
}
declare module 'eslint-plugin-jsx-a11y/lib/util/implicitRoles/a.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/lib/util/implicitRoles/a'>;
}
declare module 'eslint-plugin-jsx-a11y/lib/util/implicitRoles/area.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/lib/util/implicitRoles/area'>;
}
declare module 'eslint-plugin-jsx-a11y/lib/util/implicitRoles/article.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/lib/util/implicitRoles/article'>;
}
declare module 'eslint-plugin-jsx-a11y/lib/util/implicitRoles/aside.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/lib/util/implicitRoles/aside'>;
}
declare module 'eslint-plugin-jsx-a11y/lib/util/implicitRoles/body.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/lib/util/implicitRoles/body'>;
}
declare module 'eslint-plugin-jsx-a11y/lib/util/implicitRoles/button.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/lib/util/implicitRoles/button'>;
}
declare module 'eslint-plugin-jsx-a11y/lib/util/implicitRoles/datalist.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/lib/util/implicitRoles/datalist'>;
}
declare module 'eslint-plugin-jsx-a11y/lib/util/implicitRoles/details.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/lib/util/implicitRoles/details'>;
}
declare module 'eslint-plugin-jsx-a11y/lib/util/implicitRoles/dialog.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/lib/util/implicitRoles/dialog'>;
}
declare module 'eslint-plugin-jsx-a11y/lib/util/implicitRoles/dl.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/lib/util/implicitRoles/dl'>;
}
declare module 'eslint-plugin-jsx-a11y/lib/util/implicitRoles/form.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/lib/util/implicitRoles/form'>;
}
declare module 'eslint-plugin-jsx-a11y/lib/util/implicitRoles/h1.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/lib/util/implicitRoles/h1'>;
}
declare module 'eslint-plugin-jsx-a11y/lib/util/implicitRoles/h2.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/lib/util/implicitRoles/h2'>;
}
declare module 'eslint-plugin-jsx-a11y/lib/util/implicitRoles/h3.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/lib/util/implicitRoles/h3'>;
}
declare module 'eslint-plugin-jsx-a11y/lib/util/implicitRoles/h4.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/lib/util/implicitRoles/h4'>;
}
declare module 'eslint-plugin-jsx-a11y/lib/util/implicitRoles/h5.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/lib/util/implicitRoles/h5'>;
}
declare module 'eslint-plugin-jsx-a11y/lib/util/implicitRoles/h6.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/lib/util/implicitRoles/h6'>;
}
declare module 'eslint-plugin-jsx-a11y/lib/util/implicitRoles/hr.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/lib/util/implicitRoles/hr'>;
}
declare module 'eslint-plugin-jsx-a11y/lib/util/implicitRoles/img.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/lib/util/implicitRoles/img'>;
}
declare module 'eslint-plugin-jsx-a11y/lib/util/implicitRoles/index.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/lib/util/implicitRoles/index'>;
}
declare module 'eslint-plugin-jsx-a11y/lib/util/implicitRoles/input.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/lib/util/implicitRoles/input'>;
}
declare module 'eslint-plugin-jsx-a11y/lib/util/implicitRoles/li.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/lib/util/implicitRoles/li'>;
}
declare module 'eslint-plugin-jsx-a11y/lib/util/implicitRoles/link.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/lib/util/implicitRoles/link'>;
}
declare module 'eslint-plugin-jsx-a11y/lib/util/implicitRoles/menu.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/lib/util/implicitRoles/menu'>;
}
declare module 'eslint-plugin-jsx-a11y/lib/util/implicitRoles/menuitem.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/lib/util/implicitRoles/menuitem'>;
}
declare module 'eslint-plugin-jsx-a11y/lib/util/implicitRoles/meter.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/lib/util/implicitRoles/meter'>;
}
declare module 'eslint-plugin-jsx-a11y/lib/util/implicitRoles/nav.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/lib/util/implicitRoles/nav'>;
}
declare module 'eslint-plugin-jsx-a11y/lib/util/implicitRoles/ol.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/lib/util/implicitRoles/ol'>;
}
declare module 'eslint-plugin-jsx-a11y/lib/util/implicitRoles/option.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/lib/util/implicitRoles/option'>;
}
declare module 'eslint-plugin-jsx-a11y/lib/util/implicitRoles/output.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/lib/util/implicitRoles/output'>;
}
declare module 'eslint-plugin-jsx-a11y/lib/util/implicitRoles/progress.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/lib/util/implicitRoles/progress'>;
}
declare module 'eslint-plugin-jsx-a11y/lib/util/implicitRoles/section.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/lib/util/implicitRoles/section'>;
}
declare module 'eslint-plugin-jsx-a11y/lib/util/implicitRoles/select.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/lib/util/implicitRoles/select'>;
}
declare module 'eslint-plugin-jsx-a11y/lib/util/implicitRoles/tbody.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/lib/util/implicitRoles/tbody'>;
}
declare module 'eslint-plugin-jsx-a11y/lib/util/implicitRoles/textarea.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/lib/util/implicitRoles/textarea'>;
}
declare module 'eslint-plugin-jsx-a11y/lib/util/implicitRoles/tfoot.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/lib/util/implicitRoles/tfoot'>;
}
declare module 'eslint-plugin-jsx-a11y/lib/util/implicitRoles/thead.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/lib/util/implicitRoles/thead'>;
}
declare module 'eslint-plugin-jsx-a11y/lib/util/implicitRoles/ul.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/lib/util/implicitRoles/ul'>;
}
declare module 'eslint-plugin-jsx-a11y/lib/util/isHiddenFromScreenReader.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/lib/util/isHiddenFromScreenReader'>;
}
declare module 'eslint-plugin-jsx-a11y/lib/util/isInteractiveElement.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/lib/util/isInteractiveElement'>;
}
declare module 'eslint-plugin-jsx-a11y/lib/util/values/expressions/BinaryExpression.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/lib/util/values/expressions/BinaryExpression'>;
}
declare module 'eslint-plugin-jsx-a11y/lib/util/values/expressions/CallExpression.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/lib/util/values/expressions/CallExpression'>;
}
declare module 'eslint-plugin-jsx-a11y/lib/util/values/expressions/ConditionalExpression.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/lib/util/values/expressions/ConditionalExpression'>;
}
declare module 'eslint-plugin-jsx-a11y/lib/util/values/expressions/FunctionExpression.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/lib/util/values/expressions/FunctionExpression'>;
}
declare module 'eslint-plugin-jsx-a11y/lib/util/values/expressions/Identifier.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/lib/util/values/expressions/Identifier'>;
}
declare module 'eslint-plugin-jsx-a11y/lib/util/values/expressions/index.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/lib/util/values/expressions/index'>;
}
declare module 'eslint-plugin-jsx-a11y/lib/util/values/expressions/LogicalExpression.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/lib/util/values/expressions/LogicalExpression'>;
}
declare module 'eslint-plugin-jsx-a11y/lib/util/values/expressions/MemberExpression.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/lib/util/values/expressions/MemberExpression'>;
}
declare module 'eslint-plugin-jsx-a11y/lib/util/values/expressions/NewExpression.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/lib/util/values/expressions/NewExpression'>;
}
declare module 'eslint-plugin-jsx-a11y/lib/util/values/expressions/ObjectExpression.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/lib/util/values/expressions/ObjectExpression'>;
}
declare module 'eslint-plugin-jsx-a11y/lib/util/values/expressions/TemplateLiteral.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/lib/util/values/expressions/TemplateLiteral'>;
}
declare module 'eslint-plugin-jsx-a11y/lib/util/values/expressions/ThisExpression.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/lib/util/values/expressions/ThisExpression'>;
}
declare module 'eslint-plugin-jsx-a11y/lib/util/values/expressions/UnaryExpression.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/lib/util/values/expressions/UnaryExpression'>;
}
declare module 'eslint-plugin-jsx-a11y/lib/util/values/index.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/lib/util/values/index'>;
}
declare module 'eslint-plugin-jsx-a11y/lib/util/values/JSXElement.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/lib/util/values/JSXElement'>;
}
declare module 'eslint-plugin-jsx-a11y/lib/util/values/Literal.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/lib/util/values/Literal'>;
}
declare module 'eslint-plugin-jsx-a11y/src/index.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/src/index'>;
}
declare module 'eslint-plugin-jsx-a11y/src/rules/aria-props.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/src/rules/aria-props'>;
}
declare module 'eslint-plugin-jsx-a11y/src/rules/aria-proptypes.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/src/rules/aria-proptypes'>;
}
declare module 'eslint-plugin-jsx-a11y/src/rules/aria-role.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/src/rules/aria-role'>;
}
declare module 'eslint-plugin-jsx-a11y/src/rules/aria-unsupported-elements.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/src/rules/aria-unsupported-elements'>;
}
declare module 'eslint-plugin-jsx-a11y/src/rules/href-no-hash.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/src/rules/href-no-hash'>;
}
declare module 'eslint-plugin-jsx-a11y/src/rules/img-has-alt.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/src/rules/img-has-alt'>;
}
declare module 'eslint-plugin-jsx-a11y/src/rules/img-redundant-alt.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/src/rules/img-redundant-alt'>;
}
declare module 'eslint-plugin-jsx-a11y/src/rules/label-has-for.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/src/rules/label-has-for'>;
}
declare module 'eslint-plugin-jsx-a11y/src/rules/mouse-events-have-key-events.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/src/rules/mouse-events-have-key-events'>;
}
declare module 'eslint-plugin-jsx-a11y/src/rules/no-access-key.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/src/rules/no-access-key'>;
}
declare module 'eslint-plugin-jsx-a11y/src/rules/no-onchange.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/src/rules/no-onchange'>;
}
declare module 'eslint-plugin-jsx-a11y/src/rules/onclick-has-focus.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/src/rules/onclick-has-focus'>;
}
declare module 'eslint-plugin-jsx-a11y/src/rules/onclick-has-role.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/src/rules/onclick-has-role'>;
}
declare module 'eslint-plugin-jsx-a11y/src/rules/role-has-required-aria-props.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/src/rules/role-has-required-aria-props'>;
}
declare module 'eslint-plugin-jsx-a11y/src/rules/role-supports-aria-props.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/src/rules/role-supports-aria-props'>;
}
declare module 'eslint-plugin-jsx-a11y/src/rules/tabindex-no-positive.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/src/rules/tabindex-no-positive'>;
}
declare module 'eslint-plugin-jsx-a11y/src/util/getAttribute.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/src/util/getAttribute'>;
}
declare module 'eslint-plugin-jsx-a11y/src/util/getAttributeValue.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/src/util/getAttributeValue'>;
}
declare module 'eslint-plugin-jsx-a11y/src/util/getImplicitRole.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/src/util/getImplicitRole'>;
}
declare module 'eslint-plugin-jsx-a11y/src/util/getNodeType.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/src/util/getNodeType'>;
}
declare module 'eslint-plugin-jsx-a11y/src/util/getSuggestion.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/src/util/getSuggestion'>;
}
declare module 'eslint-plugin-jsx-a11y/src/util/getTabIndex.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/src/util/getTabIndex'>;
}
declare module 'eslint-plugin-jsx-a11y/src/util/implicitRoles/a.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/src/util/implicitRoles/a'>;
}
declare module 'eslint-plugin-jsx-a11y/src/util/implicitRoles/area.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/src/util/implicitRoles/area'>;
}
declare module 'eslint-plugin-jsx-a11y/src/util/implicitRoles/article.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/src/util/implicitRoles/article'>;
}
declare module 'eslint-plugin-jsx-a11y/src/util/implicitRoles/aside.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/src/util/implicitRoles/aside'>;
}
declare module 'eslint-plugin-jsx-a11y/src/util/implicitRoles/body.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/src/util/implicitRoles/body'>;
}
declare module 'eslint-plugin-jsx-a11y/src/util/implicitRoles/button.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/src/util/implicitRoles/button'>;
}
declare module 'eslint-plugin-jsx-a11y/src/util/implicitRoles/datalist.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/src/util/implicitRoles/datalist'>;
}
declare module 'eslint-plugin-jsx-a11y/src/util/implicitRoles/details.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/src/util/implicitRoles/details'>;
}
declare module 'eslint-plugin-jsx-a11y/src/util/implicitRoles/dialog.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/src/util/implicitRoles/dialog'>;
}
declare module 'eslint-plugin-jsx-a11y/src/util/implicitRoles/dl.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/src/util/implicitRoles/dl'>;
}
declare module 'eslint-plugin-jsx-a11y/src/util/implicitRoles/form.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/src/util/implicitRoles/form'>;
}
declare module 'eslint-plugin-jsx-a11y/src/util/implicitRoles/h1.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/src/util/implicitRoles/h1'>;
}
declare module 'eslint-plugin-jsx-a11y/src/util/implicitRoles/h2.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/src/util/implicitRoles/h2'>;
}
declare module 'eslint-plugin-jsx-a11y/src/util/implicitRoles/h3.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/src/util/implicitRoles/h3'>;
}
declare module 'eslint-plugin-jsx-a11y/src/util/implicitRoles/h4.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/src/util/implicitRoles/h4'>;
}
declare module 'eslint-plugin-jsx-a11y/src/util/implicitRoles/h5.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/src/util/implicitRoles/h5'>;
}
declare module 'eslint-plugin-jsx-a11y/src/util/implicitRoles/h6.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/src/util/implicitRoles/h6'>;
}
declare module 'eslint-plugin-jsx-a11y/src/util/implicitRoles/hr.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/src/util/implicitRoles/hr'>;
}
declare module 'eslint-plugin-jsx-a11y/src/util/implicitRoles/img.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/src/util/implicitRoles/img'>;
}
declare module 'eslint-plugin-jsx-a11y/src/util/implicitRoles/index.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/src/util/implicitRoles/index'>;
}
declare module 'eslint-plugin-jsx-a11y/src/util/implicitRoles/input.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/src/util/implicitRoles/input'>;
}
declare module 'eslint-plugin-jsx-a11y/src/util/implicitRoles/li.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/src/util/implicitRoles/li'>;
}
declare module 'eslint-plugin-jsx-a11y/src/util/implicitRoles/link.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/src/util/implicitRoles/link'>;
}
declare module 'eslint-plugin-jsx-a11y/src/util/implicitRoles/menu.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/src/util/implicitRoles/menu'>;
}
declare module 'eslint-plugin-jsx-a11y/src/util/implicitRoles/menuitem.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/src/util/implicitRoles/menuitem'>;
}
declare module 'eslint-plugin-jsx-a11y/src/util/implicitRoles/meter.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/src/util/implicitRoles/meter'>;
}
declare module 'eslint-plugin-jsx-a11y/src/util/implicitRoles/nav.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/src/util/implicitRoles/nav'>;
}
declare module 'eslint-plugin-jsx-a11y/src/util/implicitRoles/ol.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/src/util/implicitRoles/ol'>;
}
declare module 'eslint-plugin-jsx-a11y/src/util/implicitRoles/option.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/src/util/implicitRoles/option'>;
}
declare module 'eslint-plugin-jsx-a11y/src/util/implicitRoles/output.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/src/util/implicitRoles/output'>;
}
declare module 'eslint-plugin-jsx-a11y/src/util/implicitRoles/progress.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/src/util/implicitRoles/progress'>;
}
declare module 'eslint-plugin-jsx-a11y/src/util/implicitRoles/section.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/src/util/implicitRoles/section'>;
}
declare module 'eslint-plugin-jsx-a11y/src/util/implicitRoles/select.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/src/util/implicitRoles/select'>;
}
declare module 'eslint-plugin-jsx-a11y/src/util/implicitRoles/tbody.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/src/util/implicitRoles/tbody'>;
}
declare module 'eslint-plugin-jsx-a11y/src/util/implicitRoles/textarea.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/src/util/implicitRoles/textarea'>;
}
declare module 'eslint-plugin-jsx-a11y/src/util/implicitRoles/tfoot.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/src/util/implicitRoles/tfoot'>;
}
declare module 'eslint-plugin-jsx-a11y/src/util/implicitRoles/thead.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/src/util/implicitRoles/thead'>;
}
declare module 'eslint-plugin-jsx-a11y/src/util/implicitRoles/ul.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/src/util/implicitRoles/ul'>;
}
declare module 'eslint-plugin-jsx-a11y/src/util/isHiddenFromScreenReader.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/src/util/isHiddenFromScreenReader'>;
}
declare module 'eslint-plugin-jsx-a11y/src/util/isInteractiveElement.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/src/util/isInteractiveElement'>;
}
declare module 'eslint-plugin-jsx-a11y/src/util/values/expressions/BinaryExpression.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/src/util/values/expressions/BinaryExpression'>;
}
declare module 'eslint-plugin-jsx-a11y/src/util/values/expressions/CallExpression.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/src/util/values/expressions/CallExpression'>;
}
declare module 'eslint-plugin-jsx-a11y/src/util/values/expressions/ConditionalExpression.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/src/util/values/expressions/ConditionalExpression'>;
}
declare module 'eslint-plugin-jsx-a11y/src/util/values/expressions/FunctionExpression.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/src/util/values/expressions/FunctionExpression'>;
}
declare module 'eslint-plugin-jsx-a11y/src/util/values/expressions/Identifier.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/src/util/values/expressions/Identifier'>;
}
declare module 'eslint-plugin-jsx-a11y/src/util/values/expressions/index.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/src/util/values/expressions/index'>;
}
declare module 'eslint-plugin-jsx-a11y/src/util/values/expressions/LogicalExpression.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/src/util/values/expressions/LogicalExpression'>;
}
declare module 'eslint-plugin-jsx-a11y/src/util/values/expressions/MemberExpression.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/src/util/values/expressions/MemberExpression'>;
}
declare module 'eslint-plugin-jsx-a11y/src/util/values/expressions/NewExpression.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/src/util/values/expressions/NewExpression'>;
}
declare module 'eslint-plugin-jsx-a11y/src/util/values/expressions/ObjectExpression.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/src/util/values/expressions/ObjectExpression'>;
}
declare module 'eslint-plugin-jsx-a11y/src/util/values/expressions/TemplateLiteral.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/src/util/values/expressions/TemplateLiteral'>;
}
declare module 'eslint-plugin-jsx-a11y/src/util/values/expressions/ThisExpression.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/src/util/values/expressions/ThisExpression'>;
}
declare module 'eslint-plugin-jsx-a11y/src/util/values/expressions/UnaryExpression.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/src/util/values/expressions/UnaryExpression'>;
}
declare module 'eslint-plugin-jsx-a11y/src/util/values/index.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/src/util/values/index'>;
}
declare module 'eslint-plugin-jsx-a11y/src/util/values/JSXElement.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/src/util/values/JSXElement'>;
}
declare module 'eslint-plugin-jsx-a11y/src/util/values/Literal.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/src/util/values/Literal'>;
}
declare module 'eslint-plugin-jsx-a11y/tests/index.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/tests/index'>;
}
declare module 'eslint-plugin-jsx-a11y/tests/src/rules/aria-props.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/tests/src/rules/aria-props'>;
}
declare module 'eslint-plugin-jsx-a11y/tests/src/rules/aria-proptypes.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/tests/src/rules/aria-proptypes'>;
}
declare module 'eslint-plugin-jsx-a11y/tests/src/rules/aria-role.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/tests/src/rules/aria-role'>;
}
declare module 'eslint-plugin-jsx-a11y/tests/src/rules/aria-unsupported-elements.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/tests/src/rules/aria-unsupported-elements'>;
}
declare module 'eslint-plugin-jsx-a11y/tests/src/rules/href-no-hash.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/tests/src/rules/href-no-hash'>;
}
declare module 'eslint-plugin-jsx-a11y/tests/src/rules/img-has-alt.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/tests/src/rules/img-has-alt'>;
}
declare module 'eslint-plugin-jsx-a11y/tests/src/rules/img-redundant-alt.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/tests/src/rules/img-redundant-alt'>;
}
declare module 'eslint-plugin-jsx-a11y/tests/src/rules/label-has-for.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/tests/src/rules/label-has-for'>;
}
declare module 'eslint-plugin-jsx-a11y/tests/src/rules/mouse-events-have-key-events.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/tests/src/rules/mouse-events-have-key-events'>;
}
declare module 'eslint-plugin-jsx-a11y/tests/src/rules/no-access-key.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/tests/src/rules/no-access-key'>;
}
declare module 'eslint-plugin-jsx-a11y/tests/src/rules/no-onchange.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/tests/src/rules/no-onchange'>;
}
declare module 'eslint-plugin-jsx-a11y/tests/src/rules/onclick-has-focus.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/tests/src/rules/onclick-has-focus'>;
}
declare module 'eslint-plugin-jsx-a11y/tests/src/rules/onclick-has-role.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/tests/src/rules/onclick-has-role'>;
}
declare module 'eslint-plugin-jsx-a11y/tests/src/rules/role-has-required-aria-props.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/tests/src/rules/role-has-required-aria-props'>;
}
declare module 'eslint-plugin-jsx-a11y/tests/src/rules/role-supports-aria-props.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/tests/src/rules/role-supports-aria-props'>;
}
declare module 'eslint-plugin-jsx-a11y/tests/src/rules/tabindex-no-positive.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/tests/src/rules/tabindex-no-positive'>;
}
declare module 'eslint-plugin-jsx-a11y/tests/src/util/getSuggestion.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx-a11y/tests/src/util/getSuggestion'>;
}
