// flow-typed signature: bf5f2a6fb5b108036edd60b2867f64f0
// flow-typed version: <<STUB>>/immutability-helper_v2.2.0/flow_v0.53.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'immutability-helper'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'immutability-helper' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'immutability-helper/tmp' {
  declare module.exports: any;
}

// Filename aliases
declare module 'immutability-helper/index' {
  declare module.exports: $Exports<'immutability-helper'>;
}
declare module 'immutability-helper/index.js' {
  declare module.exports: $Exports<'immutability-helper'>;
}
declare module 'immutability-helper/tmp.js' {
  declare module.exports: $Exports<'immutability-helper/tmp'>;
}
