// flow-typed signature: c2909c3583a28978b8b3d7b7997967d7
// flow-typed version: <<STUB>>/jest-repl_v19.0.2/flow_v0.53.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jest-repl'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jest-repl' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jest-repl/bin/jest-repl' {
  declare module.exports: any;
}

declare module 'jest-repl/build/cli/args' {
  declare module.exports: any;
}

declare module 'jest-repl/build/cli/index' {
  declare module.exports: any;
}

declare module 'jest-repl/build/cli/repl' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jest-repl/bin/jest-repl.js' {
  declare module.exports: $Exports<'jest-repl/bin/jest-repl'>;
}
declare module 'jest-repl/build/cli/args.js' {
  declare module.exports: $Exports<'jest-repl/build/cli/args'>;
}
declare module 'jest-repl/build/cli/index.js' {
  declare module.exports: $Exports<'jest-repl/build/cli/index'>;
}
declare module 'jest-repl/build/cli/repl.js' {
  declare module.exports: $Exports<'jest-repl/build/cli/repl'>;
}
