// flow-typed signature: 9353642210e089fe04ee477bab474d7a
// flow-typed version: <<STUB>>/jpeg-js_v0.2.0/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jpeg-js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'jpeg-js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jpeg-js/lib/decoder' {
  declare module.exports: any;
}

declare module 'jpeg-js/lib/encoder' {
  declare module.exports: any;
}

declare module 'jpeg-js/test/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jpeg-js/index' {
  declare module.exports: $Exports<'jpeg-js'>;
}
declare module 'jpeg-js/index.js' {
  declare module.exports: $Exports<'jpeg-js'>;
}
declare module 'jpeg-js/lib/decoder.js' {
  declare module.exports: $Exports<'jpeg-js/lib/decoder'>;
}
declare module 'jpeg-js/lib/encoder.js' {
  declare module.exports: $Exports<'jpeg-js/lib/encoder'>;
}
declare module 'jpeg-js/test/index.js' {
  declare module.exports: $Exports<'jpeg-js/test/index'>;
}
