// flow-typed signature: dfa71ec8ec29d02b0df198669973bb7a
// flow-typed version: <<STUB>>/lessly_v0.2.4/flow_v0.53.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lessly'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'lessly' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'lessly/lib/data/colors' {
  declare module.exports: any;
}

declare module 'lessly/lib/data/index' {
  declare module.exports: any;
}

declare module 'lessly/lib/data/unit-conversions' {
  declare module.exports: any;
}

declare module 'lessly/lib/functions/color-blending' {
  declare module.exports: any;
}

declare module 'lessly/lib/functions/color' {
  declare module.exports: any;
}

declare module 'lessly/lib/functions/index' {
  declare module.exports: any;
}

declare module 'lessly/lib/functions/math-helper' {
  declare module.exports: any;
}

declare module 'lessly/lib/functions/math' {
  declare module.exports: any;
}

declare module 'lessly/lib/functions/number' {
  declare module.exports: any;
}

declare module 'lessly/lib/functions/types' {
  declare module.exports: any;
}

declare module 'lessly/lib/lessly' {
  declare module.exports: any;
}

declare module 'lessly/lib/parser/parser' {
  declare module.exports: any;
}

declare module 'lessly/lib/tree/alpha' {
  declare module.exports: any;
}

declare module 'lessly/lib/tree/anonymous' {
  declare module.exports: any;
}

declare module 'lessly/lib/tree/call' {
  declare module.exports: any;
}

declare module 'lessly/lib/tree/color' {
  declare module.exports: any;
}

declare module 'lessly/lib/tree/dimension' {
  declare module.exports: any;
}

declare module 'lessly/lib/tree/index' {
  declare module.exports: any;
}

declare module 'lessly/lib/tree/keyword' {
  declare module.exports: any;
}

declare module 'lessly/lib/tree/negative' {
  declare module.exports: any;
}

declare module 'lessly/lib/tree/node' {
  declare module.exports: any;
}

declare module 'lessly/lib/tree/operation' {
  declare module.exports: any;
}

declare module 'lessly/lib/tree/quoted' {
  declare module.exports: any;
}

declare module 'lessly/lib/tree/unit' {
  declare module.exports: any;
}

declare module 'lessly/lib/tree/value' {
  declare module.exports: any;
}

declare module 'lessly/lib/utils' {
  declare module.exports: any;
}

declare module 'lessly/src/data/colors' {
  declare module.exports: any;
}

declare module 'lessly/src/data/index' {
  declare module.exports: any;
}

declare module 'lessly/src/data/unit-conversions' {
  declare module.exports: any;
}

declare module 'lessly/src/functions/color-blending' {
  declare module.exports: any;
}

declare module 'lessly/src/functions/color' {
  declare module.exports: any;
}

declare module 'lessly/src/functions/index' {
  declare module.exports: any;
}

declare module 'lessly/src/functions/math-helper' {
  declare module.exports: any;
}

declare module 'lessly/src/functions/math' {
  declare module.exports: any;
}

declare module 'lessly/src/functions/number' {
  declare module.exports: any;
}

declare module 'lessly/src/functions/types' {
  declare module.exports: any;
}

declare module 'lessly/src/lessly' {
  declare module.exports: any;
}

declare module 'lessly/src/parser/parser' {
  declare module.exports: any;
}

declare module 'lessly/src/tree/alpha' {
  declare module.exports: any;
}

declare module 'lessly/src/tree/anonymous' {
  declare module.exports: any;
}

declare module 'lessly/src/tree/call' {
  declare module.exports: any;
}

declare module 'lessly/src/tree/color' {
  declare module.exports: any;
}

declare module 'lessly/src/tree/dimension' {
  declare module.exports: any;
}

declare module 'lessly/src/tree/index' {
  declare module.exports: any;
}

declare module 'lessly/src/tree/keyword' {
  declare module.exports: any;
}

declare module 'lessly/src/tree/negative' {
  declare module.exports: any;
}

declare module 'lessly/src/tree/node' {
  declare module.exports: any;
}

declare module 'lessly/src/tree/operation' {
  declare module.exports: any;
}

declare module 'lessly/src/tree/unit' {
  declare module.exports: any;
}

declare module 'lessly/src/utils' {
  declare module.exports: any;
}

declare module 'lessly/test/functions' {
  declare module.exports: any;
}

declare module 'lessly/test/index' {
  declare module.exports: any;
}

declare module 'lessly/test/lessly' {
  declare module.exports: any;
}

// Filename aliases
declare module 'lessly/index' {
  declare module.exports: $Exports<'lessly'>;
}
declare module 'lessly/index.js' {
  declare module.exports: $Exports<'lessly'>;
}
declare module 'lessly/lib/data/colors.js' {
  declare module.exports: $Exports<'lessly/lib/data/colors'>;
}
declare module 'lessly/lib/data/index.js' {
  declare module.exports: $Exports<'lessly/lib/data/index'>;
}
declare module 'lessly/lib/data/unit-conversions.js' {
  declare module.exports: $Exports<'lessly/lib/data/unit-conversions'>;
}
declare module 'lessly/lib/functions/color-blending.js' {
  declare module.exports: $Exports<'lessly/lib/functions/color-blending'>;
}
declare module 'lessly/lib/functions/color.js' {
  declare module.exports: $Exports<'lessly/lib/functions/color'>;
}
declare module 'lessly/lib/functions/index.js' {
  declare module.exports: $Exports<'lessly/lib/functions/index'>;
}
declare module 'lessly/lib/functions/math-helper.js' {
  declare module.exports: $Exports<'lessly/lib/functions/math-helper'>;
}
declare module 'lessly/lib/functions/math.js' {
  declare module.exports: $Exports<'lessly/lib/functions/math'>;
}
declare module 'lessly/lib/functions/number.js' {
  declare module.exports: $Exports<'lessly/lib/functions/number'>;
}
declare module 'lessly/lib/functions/types.js' {
  declare module.exports: $Exports<'lessly/lib/functions/types'>;
}
declare module 'lessly/lib/lessly.js' {
  declare module.exports: $Exports<'lessly/lib/lessly'>;
}
declare module 'lessly/lib/parser/parser.js' {
  declare module.exports: $Exports<'lessly/lib/parser/parser'>;
}
declare module 'lessly/lib/tree/alpha.js' {
  declare module.exports: $Exports<'lessly/lib/tree/alpha'>;
}
declare module 'lessly/lib/tree/anonymous.js' {
  declare module.exports: $Exports<'lessly/lib/tree/anonymous'>;
}
declare module 'lessly/lib/tree/call.js' {
  declare module.exports: $Exports<'lessly/lib/tree/call'>;
}
declare module 'lessly/lib/tree/color.js' {
  declare module.exports: $Exports<'lessly/lib/tree/color'>;
}
declare module 'lessly/lib/tree/dimension.js' {
  declare module.exports: $Exports<'lessly/lib/tree/dimension'>;
}
declare module 'lessly/lib/tree/index.js' {
  declare module.exports: $Exports<'lessly/lib/tree/index'>;
}
declare module 'lessly/lib/tree/keyword.js' {
  declare module.exports: $Exports<'lessly/lib/tree/keyword'>;
}
declare module 'lessly/lib/tree/negative.js' {
  declare module.exports: $Exports<'lessly/lib/tree/negative'>;
}
declare module 'lessly/lib/tree/node.js' {
  declare module.exports: $Exports<'lessly/lib/tree/node'>;
}
declare module 'lessly/lib/tree/operation.js' {
  declare module.exports: $Exports<'lessly/lib/tree/operation'>;
}
declare module 'lessly/lib/tree/quoted.js' {
  declare module.exports: $Exports<'lessly/lib/tree/quoted'>;
}
declare module 'lessly/lib/tree/unit.js' {
  declare module.exports: $Exports<'lessly/lib/tree/unit'>;
}
declare module 'lessly/lib/tree/value.js' {
  declare module.exports: $Exports<'lessly/lib/tree/value'>;
}
declare module 'lessly/lib/utils.js' {
  declare module.exports: $Exports<'lessly/lib/utils'>;
}
declare module 'lessly/src/data/colors.js' {
  declare module.exports: $Exports<'lessly/src/data/colors'>;
}
declare module 'lessly/src/data/index.js' {
  declare module.exports: $Exports<'lessly/src/data/index'>;
}
declare module 'lessly/src/data/unit-conversions.js' {
  declare module.exports: $Exports<'lessly/src/data/unit-conversions'>;
}
declare module 'lessly/src/functions/color-blending.js' {
  declare module.exports: $Exports<'lessly/src/functions/color-blending'>;
}
declare module 'lessly/src/functions/color.js' {
  declare module.exports: $Exports<'lessly/src/functions/color'>;
}
declare module 'lessly/src/functions/index.js' {
  declare module.exports: $Exports<'lessly/src/functions/index'>;
}
declare module 'lessly/src/functions/math-helper.js' {
  declare module.exports: $Exports<'lessly/src/functions/math-helper'>;
}
declare module 'lessly/src/functions/math.js' {
  declare module.exports: $Exports<'lessly/src/functions/math'>;
}
declare module 'lessly/src/functions/number.js' {
  declare module.exports: $Exports<'lessly/src/functions/number'>;
}
declare module 'lessly/src/functions/types.js' {
  declare module.exports: $Exports<'lessly/src/functions/types'>;
}
declare module 'lessly/src/lessly.js' {
  declare module.exports: $Exports<'lessly/src/lessly'>;
}
declare module 'lessly/src/parser/parser.js' {
  declare module.exports: $Exports<'lessly/src/parser/parser'>;
}
declare module 'lessly/src/tree/alpha.js' {
  declare module.exports: $Exports<'lessly/src/tree/alpha'>;
}
declare module 'lessly/src/tree/anonymous.js' {
  declare module.exports: $Exports<'lessly/src/tree/anonymous'>;
}
declare module 'lessly/src/tree/call.js' {
  declare module.exports: $Exports<'lessly/src/tree/call'>;
}
declare module 'lessly/src/tree/color.js' {
  declare module.exports: $Exports<'lessly/src/tree/color'>;
}
declare module 'lessly/src/tree/dimension.js' {
  declare module.exports: $Exports<'lessly/src/tree/dimension'>;
}
declare module 'lessly/src/tree/index.js' {
  declare module.exports: $Exports<'lessly/src/tree/index'>;
}
declare module 'lessly/src/tree/keyword.js' {
  declare module.exports: $Exports<'lessly/src/tree/keyword'>;
}
declare module 'lessly/src/tree/negative.js' {
  declare module.exports: $Exports<'lessly/src/tree/negative'>;
}
declare module 'lessly/src/tree/node.js' {
  declare module.exports: $Exports<'lessly/src/tree/node'>;
}
declare module 'lessly/src/tree/operation.js' {
  declare module.exports: $Exports<'lessly/src/tree/operation'>;
}
declare module 'lessly/src/tree/unit.js' {
  declare module.exports: $Exports<'lessly/src/tree/unit'>;
}
declare module 'lessly/src/utils.js' {
  declare module.exports: $Exports<'lessly/src/utils'>;
}
declare module 'lessly/test/functions.js' {
  declare module.exports: $Exports<'lessly/test/functions'>;
}
declare module 'lessly/test/index.js' {
  declare module.exports: $Exports<'lessly/test/index'>;
}
declare module 'lessly/test/lessly.js' {
  declare module.exports: $Exports<'lessly/test/lessly'>;
}
