// flow-typed signature: 8cad8ab08a0b00ab21ce69ba005124b0
// flow-typed version: <<STUB>>/react-native-device-info_v0.11.0/flow_v0.53.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-device-info'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-device-info' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-device-info/deviceinfo' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-device-info/deviceinfo.js' {
  declare module.exports: $Exports<'react-native-device-info/deviceinfo'>;
}
