// flow-typed signature: a7187e343391a2920936b65aee1297c2
// flow-typed version: <<STUB>>/@yfuks/react-native-action-sheet_vgit+https://github.com/doubleqliq/react-native-action-sheet.git/flow_v0.53.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@yfuks/react-native-action-sheet'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@yfuks/react-native-action-sheet' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@yfuks/react-native-action-sheet/Example/index.android' {
  declare module.exports: any;
}

declare module '@yfuks/react-native-action-sheet/Example/index.ios' {
  declare module.exports: any;
}

declare module '@yfuks/react-native-action-sheet/Example/index' {
  declare module.exports: any;
}

// Filename aliases
declare module '@yfuks/react-native-action-sheet/Example/index.android.js' {
  declare module.exports: $Exports<'@yfuks/react-native-action-sheet/Example/index.android'>;
}
declare module '@yfuks/react-native-action-sheet/Example/index.ios.js' {
  declare module.exports: $Exports<'@yfuks/react-native-action-sheet/Example/index.ios'>;
}
declare module '@yfuks/react-native-action-sheet/Example/index.js' {
  declare module.exports: $Exports<'@yfuks/react-native-action-sheet/Example/index'>;
}
declare module '@yfuks/react-native-action-sheet/index' {
  declare module.exports: $Exports<'@yfuks/react-native-action-sheet'>;
}
declare module '@yfuks/react-native-action-sheet/index.js' {
  declare module.exports: $Exports<'@yfuks/react-native-action-sheet'>;
}
